# Generated by Django 3.2.13 on 2022-06-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
